### PR TITLE
run max_vids over pagination

### PR DESCRIPTION
**Pull request by dromer**
Because lbrynet has an maximum page size of 50, it's better to traverse all pages if one wants to mirror a selection larger than this number.

Instead the config will say a maximum number of vids `max_vids` can be mirrored and we will traverse the directory until either this maximum is reached or we run out of items.

There is obviously some code redundancy here. I can help refactor the daemon check to where it can be more easily reused if needed.

### CODE REVIEW

**Comment by dromer** [comment]
Saw a logic error + did the refactor.

What do you think? :)

**Comment by tuxfoo** [comment]
Sounds like a good idea, I will take a look when I have time.
Maybe we could also implement https://github.com/tuxfoo/lbry-seedit/issues/16 at the same time.

**Comment by dromer** [comment]
yeah I was thinking the same thing actually. could be a relatively small tweak to this

**Comment by dromer** [comment]
<3

**Pull request merged**
