### PR TITLE
Dockerized and restructured project 

### LINKED ISSUE #2: Add check for systemd service file
lbrynet is managed by systemd and it is not running then start lbrynet via systemd.

### PR DESCRIPTION
**Pull request by zmunro**
There are a lot of changes in this PR. The main ones being:

- The project structure has evolved significantly, into something more similar to a production repository
- There are no longer any prerequisites to install besides Docker and Docker-compose, instructions are linked in the readme as to how to do this.
- Most project files related to code execution was moved into `seedit/core`. In my experience, this is a good way to setup projects that utilize docker-compose. You place your docker-compose files, readmes, and other basic things in the top level directory. Then you have a folder for each docker service you are running (in this case just one called seedit). Then in those folders, you have the Dockerfile for the container, and a `core` folder that gets mounted into the container.
- I copied a decent amount of code for the dockerfile and associated lbrynet files that startup that container from this other repository: (lbry-docker)[https://github.com/lbryio/lbry-docker/tree/master/lbrynet]

The main `lbry-seedit.py` script could definitely use some updating. It makes some assumptions about where files are that are not clear. I also commented out some code that checks to see if `lbrynet` is running, because we now know that it is definitely running in the docker container, and that the `lbrynet` executable is in your PATH.

Documentation is the biggest thing that this repository will benefit from. You have to assume that someone reading the readme has ZERO experience with what lbry is or what seeding is. At the very least, point them to an article or documents where they can get the background knowledge they need. Include details about HOW people can contribute to the project if they want to.

### CODE REVIEW

**Comment by tuxfoo** [comment]
Cool, dockerizing is a good idea as more features may get added and some consumer NAS devices come with docker support.

Will take a look at it and do some testing.

Might be a good idea to use the following as a example of how to run the container, so the user can get an idea of how to change where the files will be stored.
```
docker-compose up -d -v /srv/lbrynet:/home/lbrynet
```
Definitely need to work on my documentation game, never been good at it.

**Comment by zmunro** [comment]
@tuxfoo Good idea, right now it just stores the files in a `seedit/core/lbrynet_home/Downloads`

**Comment by zmunro** [comment]
Some future work might be to add something that runs the python script periodically.

I also added some better error handling to that script, since I was getting errors that didn't have anything to do with what the problem really was.

**Comment by tuxfoo** [comment]
Merged this with https://github.com/tuxfoo/lbry-seedit/pull/7

Cheers.

**Pull request closed without merging**
